# SearXNG settings for Scuba Browser
# see https://docs.searxng.org/admin/settings/settings.html

use_default_settings: true

general:
  # Debug mode, only for development
  debug: false
  # displayed name
  instance_name: "Scuba Search"
  # contact: mailto:contact@example.com
  # privacy_policy_url: https://example.com/privacy
  # donation_url: https://example.com/donate
  # contact_url: https://example.com/contact
  # git_url: https://github.com/searxng/searxng
  # git_branch: master
  # issue_url: https://github.com/searxng/searxng/issues

search:
  # Filter results. 0: None, 1: Moderate, 2: Strict
  safe_search: 0
  # Use Google for autocomplete only
  autocomplete: "google"
  # minimun characters to type before autocompleting
  autocomplete_min: 4
  # Default search language - leave blank to detect from browser information or
  # use codes from languages.py
  default_lang: ""
  # max ban time in seconds after engine errors
  ban_time_on_fail: 5
  # max ban time in seconds after engine timeout
  max_ban_time_on_fail: 120
  # remove format to deny access, use lower case.
  # formats: [html, csv, json, rss]
  formats:
    - html
    - json
  # Only use enabled engines (Google only)
  default_engines: ["google"]

server:
  # If you change port, don't forget to change it in uwsgi.ini
  port: 8080
  bind_address: "0.0.0.0"
  # public URL of the instance, to ensure correct inbound links. Is overwritten by ${SEARXNG_BASE_URL}.
  base_url: false  # "https://example.org/location"
  # The maximum HTTP request body size in bytes
  max_request_timeout: 20.0
  # server limiter
  limiter: false  # rate limit the number of request on the instance, block some bots
  # Secret key for securing sessions - SECURITY: Use environment variable
  secret_key: "${SEARXNG_SECRET_KEY}"

ui:
  # Custom static path - leave it blank if you didn't change
  static_path: ""
  # Custom templates path - leave it blank if you didn't change
  templates_path: ""
  # query_in_title: When true, the result page's titles contains the query
  query_in_title: true
  # infinite_scroll: When true, automatically loads the next page when scrolling to bottom of current page.
  infinite_scroll: false
  # ui theme
  default_theme: simple
  # center the results ?
  center_alignment: false
  # URL prefix of the internet archive, don't forget trailing slash (if needed).
  # cache_url: "https://web.archive.org/web/"
  # Default interface locale - leave blank to detect from browser information or
  # use codes from languages.py
  default_locale: ""
  # Open result links in a new tab by default
  # results_on_new_tab: false

# Redis cache settings
redis:
  url: redis://redis:6379/0

# Lock arbitrary settings on the preferences page. To find the ID of the user
# setting you want to lock, check the ID of the form on the page "preferences".
# preferences:
#   lock:
#     - autocomplete
#     - method
#     - query_in_title

# searx supports result proxification using an external service:
# https://github.com/asciimoo/morty
# uncomment below section if you have running morty proxy the key is base64 encoded (keep the !!binary notation)
# the WSGI server (uwsgi or gunicorn) have to be restarted after this change
# result_proxy:
#   url: http://127.0.0.1:3000/
#   key: !!binary "your_morty_proxy_key"
#   proxify_results: true

# Communication with search engines
outgoing:
  # default timeout in seconds, can be override by engine
  request_timeout: 3.0
  # the maximum timeout in seconds
  max_request_timeout: 10.0
  # default pages to load, can be override by engine
  default_http_headers:
    User-Agent: SearXNG-bot

# Engine preferences - Google only for cleaner, focused results
engines:
  # Only Google enabled for best quality results
  - name: google
    disabled: false
    shortcut: g
  
  # Disable ALL other engines explicitly
  - name: brave
    disabled: true
  - name: duckduckgo
    disabled: true
  - name: bing
    disabled: true
  - name: startpage
    disabled: true
  - name: yahoo
    disabled: true
  - name: wikipedia
    disabled: true
  - name: reddit
    disabled: true
  - name: github
    disabled: true
  - name: stackoverflow
    disabled: true
  - name: youtube
    disabled: true
  - name: twitter
    disabled: true
  - name: wikidata
    disabled: true
  - name: qwant
    disabled: true
  - name: yandex
    disabled: true
  - name: searx
    disabled: true
